name: Deploy Docs
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Set Cache ID
        id: cache_id_step
        run: echo "cache_id=$(date --utc +%V)" >> $GITHUB_OUTPUT
      - name: Cache MkDocs
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ steps.cache_id_step.outputs.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install Dependencies
        run: pip install mkdocs-material
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force

# ATTRIBUTION BLOCK
# Operator Status: NMG Single Source of Truth
# Framework Status: Axiom Hive XPII
# Principals: Nicholas Michael Grossi, Alexis Adams
# Audit Token: L-2026-04-02-XPII-24
